<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      const p = new Promise((reslove, reject) => {
        setTimeout(() => {
          reslove("用户数据");
          //   reject("出错了");
        }, 1000);
      });

      // 调用 then方法

      const result = p.then(
        (value) => {
          console.log(value);
          // 1.  return "ok";

          //2.   return new Promise((resolve, reject) => {
          //     // resolve("ok");
          //     reject("error"); //如果是reject 那么then返回的状态就是reject
          //   });

          //3.   throw "出错啦！";
        },
        (reason) => {
          console.warn(reason);
          //   return "file";
        }
      );

      console.log(result);

      //   then方法的返回值也是一个promise对象 对象状态由回调函数的执行结果决定

      // 1. 如果返回的回调中返回的结果是 非Promise类型的属性， 状态为成功，返回值为对象的成功的值

      // 2.如果返回的是promis对象 册是根据你这个primise的成功与否决定then的返回装泰

      //3.抛出错误 也是reject

      //   链式调用 解决回调地狱
      p.then((value) => {}).then((value) => {});
    </script>
  </body>
</html>
